# Generated by Django 3.0 on 2019-12-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191213_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_confirmations', to='restaurant.Profile')),
                ('cooker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooker_requests', to='restaurant.Profile')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_request', to='restaurant.Food')),
            ],
        ),
    ]
